### ISSUE TITLE
Use with Stellarmate OS

### ISSUE THREAD

**Issue by mbalkham** [mworion/MountWizzard4#103]
Is it possible to install and run mountwizzard4 on a rpi4 running the Stellarmate OS? I'm struggling to update python to 3.8.5 on that system. I've followed instructions and done a fresh install of Ubuntu server and Ubuntu mate desktop and got a running version of mountwizzard4. This is problematic with my setup (requiring logins, configuring hotspot, multiple prolific drivers, etc. ). All of those issues have been resolved with stellarmate (raspbian based).

**Comment by mworion** [comment]
Hi,
honestly speaking: I do not know. Minimum requirement would be python 3.7, so if stellarmate supports this, you don't have to change the python. If it's more to do I cannot help, sorry.
Michel

**Comment by Raddock** [comment]
I had not ever run MW4 on the Stellarmate, only on my Mac, as the environment I'm in (my home network) allows me to run the StellarMate using the INDI Server mode, and I can run KStars/EKOS and MW4 on my Mac, or KSTars/EKOS on the StellarMate and MW4 on my Mac. So I never tried to run both on the StellarMate.

The latest StellarMate image is running Raspbian. It comes with Python 2.7. Which is not compatible with MW4. So you have to upgrade to 3.8 which can only be done by compiling from source. Easy enough: there is a tutorial here to do that. https://installvirtual.com/how-to-install-python-3-8-on-raspberry-pi-raspbian/

This takes about 20 minutes from start to finish to download and compile then make a symlink to default to running Python 3.8 --version checks out. Now virtual environment is not running, so install it using the commands here. https://raspberrypi.stackexchange.com/questions/53568/installation-problems-in-virtualenv

Unfortunately this installs virtualenv inside the Python 2.7 version. So when you execute the MW4 install script it puts Python 2.7 into the MW4/venv/lib folder. And of course MW4 will not run.

This is where I'm stuck. I would suppose Python 2.7 needs to be removed. Somehow strangely if you run Python3 --V you get Python 3.7, and since creating the symlink running Python --V you get Python 3.8. So it appears now that three Python versions are installed.

**Comment by Raddock** [comment]
Here's my install log. 
[install.log](https://github.com/mworion/MountWizzard4/files/5751503/install.log)

**Comment by mworion** [comment]
Hi,
if you have different python version installed, the script might not handle this correctly on rasping.
Try to get an overview of the python versions installed:

python --version
python3 --version

you also could check (but this might bit different on rasping) with starting the python interpreter:

python3

and check the output. leaving it with

exit()

To install manually the venv the right command would be:

python3 -m venv venv

This normally installs the python3 version you get with python3 --version in the terminal.
Next step would be to open the venv for usage:

source venv/bin/activate

check the installed python version inside venv with
python --version

You should see a prefix in your prompt, most likely the prefix is "(venv)"
after that install MountWizzard4 with

pip install mountwizzard4

and wait.
the run script should contain

source venv/bin/activate
python venv/lib/python3.7/site-packages/mw4/loader.py

where python3.7 needs to be the python version install in the venv.

Hope this will work.
Michel

**Comment by Raddock** [comment]
python --version reports Python 3.8.0
python3 --version reports Python 3.7.3

It did not quite work. Here's what it looked like in the terminal. 
<img width="1040" alt="Screen Shot 2020-12-29 at 3 49 00 PM" src="https://user-images.githubusercontent.com/5283143/103316211-6e355d80-49ed-11eb-9493-1b74f769b8a1.png">

**Comment by mworion** [comment]
Hi,
you have a spelling error in you last command:
mountwizard4 and should be mountwizzard4 (double 'z')
that's the reason you don't find anything.
Michel

**Comment by Raddock** [comment]
Michel, It installed this time. Thanks! 

<img width="921" alt="Screen Shot 2020-12-30 at 7 33 42 AM" src="https://user-images.githubusercontent.com/5283143/103354581-8a7ade00-4a71-11eb-84ee-129b7fa0d57f.png">

Now on the last part, you mention the run script needs to contain those two items. And when I open it, it does appear to have them. The variables work and it executes with python3.7 in the command, but gets an error.

<img width="629" alt="Screen Shot 2020-12-30 at 7 39 53 AM" src="https://user-images.githubusercontent.com/5283143/103354856-4c31ee80-4a72-11eb-83f9-4f5e00303caa.png">

**Comment by mworion** [comment]
The line which is listed contains no error. 
Try to start is manually without a script. Change to you working directory (where mw4 is installed to and where venv is in) and do
source venv/bin/activate

and then from there

python venv/lib/python3.7/site-packages/mw4/loader.py

Michel

**Comment by Raddock** [comment]
Here's the response I get. 

<img width="820" alt="Screen Shot 2020-12-30 at 9 34 30 AM" src="https://user-images.githubusercontent.com/5283143/103364027-447a4600-4a82-11eb-87ee-ee1a82409dc5.png">

If this starts to get too complicated to solve easily, just let me know.

**Comment by mworion** [comment]
No problem about this.
My guess (as I do not know stellarmate is that's a arm7 solution most probable based on a raspi3. If so there is a lot of handwork (see RPi3 install) to be made. I tried it once with an RPi3 under ubuntu mate, but this was not nice as you have to build a lot of packages yourself (means compiling PYQt5 etc)
Michel

**Comment by mbalkham** [comment]
Thanks both more progress than I managed! I'm now up to try 7 with an ubuntu mate desktop install trying to recreate all the stellarmate things I use. I've given up trying to get it to work on Stellarmate (for now) though I might reach out to Jasem and see if he has any advice on getting it to work on his platform.

**Comment by mworion** [comment]
If you managed to get it run, please describe the way you went. This might help others. I will include your experience in the documentation for that.
Michel

**Comment by mbalkham** [comment]
I really can't recall what I was doing. I have made notes though. When I say I got it to work, not the full install but managed to get python 3.8.5 and virtualenv running. It still didn't install MW4. 

I've had a response from the Stellarmate team who will consider looking into this on a future version. That sounds like our best chance rather than me stabbing around in the dark!

**Comment by mworion** [comment]
OK,
I close this point. As soon as you have some support from them, please reopen it or open a new issue.
Michel
