### ISSUE TITLE
Info request

### ISSUE THREAD

**Issue by gpassera** [mworion/MountWizzard4#105]
How can I disable the automatic deletion of the model when I generate a new one?
MW4 on Windows.

Thank you and regards
Giuseppe

**Comment by mworion** [comment]
Giuseppe,
Actually you can't. Is there a need doing that ? If so I could add a checkbox for that. But the model will be anyway declared once the new is in.
Michel

**Comment by gpassera** [comment]
Michel
Thanks for the very fast replay
No, I don't' need but I saw that also the initial 3 points are deleted when you make the refinement model and I was a little bit surprised. This means that making the initial 3 points become a useless operation.

Thanks and regards

Giuseppe

**Comment by mworion** [comment]
Giuseppe,
I put it in anyway. It will be in the release 0.230.1, it's almost done because only few line of code.

But as a remark: the whole discussion about the 3 initial points went in the wrong direction. There is not any difference between the first three and other points in the mount. Also special treatment these 'initial' points is lost energy. The real facts about three points is, that the mount computer needs at least 3 points to make a full model calculation with correction of all possible errors. Still 3 points will never be sufficient to give a good model, but with less there from maths no chance to calculate any.

You should choose all your points reasonably (well distributed, ....). The discussion probable started once the model build was done manually. There you only could get an interactive way and you might not have a fast plate solver or you have to find the reference stars manually. In this case it would be very helpful that you get the 'best' model with 3 initial points as possible, because that will make life for the next points much more easy. Today with modeling software you just don't care, because the work is done from a computer, which knows about all the stars.

Michel

**Comment by gpassera** [comment]
Michel

I agree with you. The three starting points are a legacy of manual modeling considering that since I use mountwizzard 4 by eliminating the 3 starting points when I refine I still have very good rms and the mount follows just as well.

Thank you very much as usual and again many compliments for your invaluable product.
Giuseppe

**Comment by gpassera** [comment]
Solved thank you
