### ISSUE TITLE
Feature suggestion: clock sync mount -> computer

### ISSUE THREAD

**Issue by razvan-astro** [mworion/MountWizzard4#109]
Hi Michel,

I would like to suggest a feature that would be helpful, I think, to users having mounts sync'ed with a GPS unit such as MGBox.  When using a computer in the field, the user may notice the computer time is not correct but without internet it's not possible to use NTP to correct the clock. Although the mount will operate correctly, it'd be convenient for the computer to have the same time. 

Thus, my suggestion is to add a button to sync the computer time based on the return of either #GLDT# (local time) or #GUDT#.  Using the latter will be more correct if MW4 can read the time zone from the computer and calculate the offset. Or, for simplicity, assume the computer and the mount are already set to the same time zone and using the local time  (although this assumption, like many assumptions, might create some problems). You'll know better which is appropriate.

10Micron has a utility to sync the time from the computer to the mount, but I'm asking about the reverse. Also, with MGBox it's possible to connect it to the computer over USB and sync and connect it back to the mount, but that's extra hassle. 

Thanks for considering it.

**Comment by mworion** [comment]
Hi Razvan,

a topic to think about as MW4 does use the timebase of the mount anyway for all computations. Question: how precise you would like two have the time synced ? Easy: just write the received time from mount to computer as well. This is about 100-200 ms real difference depending on the round trip time for everything. This would increase complexity and was the reason not to implement the sync option 10micron has in MW4 as well.

What do you think ?
Michel

**Comment by Ruediger3** [comment]
Hi Michael, Hi Razvan,

if you have a strtum1 clock connected, like a GPS receiver, you get down to 1-2 ms preciseness. 
But therefore some modification of Windows registry is required in order to switch windows in high precision mode.
I have done that and sync the mount every second. Result dramatic less problems.

Please see also Microsoft's writing on that: Microsoft time modes and configuration:
https://docs.microsoft.com/de-de/windows-server/networking/windows-time-service/windows-time-service-top

Note: Can be switched to English reading on top right "Auf Englisch lesen"

**Comment by razvan-astro** [comment]
Hi Michel and Rüdiger,

The use case I had in mind was a one-time sync, triggered by the user by clicking a button, upon noticing the computer clock is off (which means it's really off, not just by fractions of seconds). For instance, if the telescope is controlled by a NUC with a bad internal clock battery - when the NUC is booted up, the clock can be off by days or even more and without an internet connection, it requires manual setup every time (while powered on, the clock is ok).

I wasn't thinking of a high precision sync nor of a periodic one, just a one-time correction of the clock. In this case, having a difference of 100-200ms is ok since the computer clock is not used for anything else requiring more precision and it's higher than what the user would obtain manually anyway. To avoid confusion, this option could be named "Set clock from mount" instead of "sync clock" which sort of implies higher precision or periodic corrections.

**Comment by mworion** [comment]
Razvan,

I do a really simple push to computer. Please take into account that time setting has to be allowed from user side. Otherwise we start with a mess about password etc...

Michel

**Comment by razvan-astro** [comment]
Sure, that'd be great. And again, I'm not suggestion anything automatic, just a button for the user to click on. 

Thank you.

**Comment by Ruediger3** [comment]
Hi Razvan,

I only jumped in because I had the same controversy with 10M a while ago. It turned out that the precision modes of Windows and also Linux was not really know by 10M support. 

Basically it is a very clever idea to synchronize to a local GPS since this is one one the best time clocks you can get. And I totally agree on that this is the best time source when you are mobile or offline. For sure!

Cheers
Rüdiger

**Comment by mworion** [comment]
Available in v1.1.0b0 beta. Please reopen if problems occur.

**Comment by razvan-astro** [comment]
Thanks Michel, that was fast!
