### ISSUE TITLE
mountwizzard4 v1.0.5 is broken on pypi

### ISSUE THREAD

**Issue by IslamAlam** [mworion/MountWizzard4#121]
Hi @mworion,

The mountwizzard4 is broken on ARM (Jetson Nano) devices due to the issue with NumPy library 1.19.3

https://pypi.org/project/mountwizzard4/1.0.5/

This is the current error:
```
(venv) astronomer@jetson-observatory:~/mountwizzard4$ python ./venv/lib/python3.8/site-packages/mw4/loader.py 
RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd
Traceback (most recent call last):
  File "./venv/lib/python3.8/site-packages/mw4/loader.py", line 36, in <module>
    import matplotlib
  File "/home/astronomer/mountwizzard4/venv/lib/python3.8/site-packages/matplotlib/__init__.py", line 174, in <module>
    _check_versions()
  File "/home/astronomer/mountwizzard4/venv/lib/python3.8/site-packages/matplotlib/__init__.py", line 159, in _check_versions
    from . import ft2font
ImportError: numpy.core.multiarray failed to import
```

To resolve it on the installation, consider forcing the upgrade of NumPy as the following:

`pip uninstall numpy && pip install numpy==1.20.1`

**Comment by mworion** [comment]
HI @IslamAlam,

I do not see that MW4 is broken on PyPI. MW4 supports aarch64, if you build your packages yourself. Sometimes PyPi does not provide these packages for ARM. Your problem is related to numpy and matplotlib and knows in some other use cases, too. There is no way to solve this within MW4 purely. If you have a procedure to overcome this issue with a script or description, I'm pleased to add this to the documentation for your Nvidia board.

Michel
