### ISSUE TITLE
Connection QHY cameras

### ISSUE THREAD

**Issue by mworion** [mworion/MountWizzard4#125]
Today I am trying to set up another camera, a QHYCCD. I noticed that MW4 cannot connected to QHY camera or filter wheel. I selected QHY camera in ASCOM as normal but once set up it won't connect and throw off error. Before & after MW4 error, I tried QHY ascom connection via other program (skyX and Voyager) and they both recognize the camera & filterwheel fine and connected fine. Attached please find the related logbook (I tried a few times, so a few repeated error messages..). My current QHY driver is at v20.06.26.36. Do you have any clue what might be wrong with QHY camera connection within MW4?

ASCOM connection error
[mw4-2021-02-27.log](https://github.com/mworion/MountWizzard4/files/6054297/mw4-2021-02-27.log)

**Comment by mworion** [comment]
Still the QCI updater is not found (so upload functions might not work with MW4 automation)
The QHY topic is related that MW4 could not connect to the ASCOm driver. 

- do you use 64bit versions of voyager and tsx?
- is the QHY driver a 32bit or 64bit driver?

**Comment by yzhzhang** [comment]
Hi Michel,

The driver seems to be 32bit but I am not sure. Voyager I think is for sure 32bit; SkyX I think so too. My operating system is 64bit.

Today with some luck (powering off / on the camera a bit) I for once was able to get the camera only connected to MW4 (didn't bother with filter wheel). However once I start a single exposure, the message window showed it start exposing, but then it crashes and it throws an error message something like "Python stopped working". I think it happened right after I click the "expose", so one example is 2-28 03:00:46 in the attached log.
[mw4-2021-02-28.log](https://github.com/mworion/MountWizzard4/files/6057859/mw4-2021-02-28.log)

After that MW4 is not able to find the camera, even though I can still see from other softwares in ASCOM camera selection menu. In MW4 when selecting the camera I am getting this error message; noted that in the red box where you select the camera, it used to have the complete serial number of my QHY16200 camera (and I still see that in other programs); but now it doesn't show fully, and when selecting this camera option, it throw error below:
![image](https://user-images.githubusercontent.com/79808935/109431727-d50acf00-79bc-11eb-93e8-317c8077c261.png)

The detailed error message is copied below.
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at ASCOM.QHYCCD.libqhyccd.OpenQHYCCD(StringBuilder id)
   at ASCOM.QHYCCD.SetupDialogForm.QueryCamProperties()
   at ASCOM.QHYCCD.SetupDialogForm.coboCamereName_SelectedIndexChanged(Object sender, EventArgs e)
   at System.Windows.Forms.ComboBox.OnSelectedIndexChanged(EventArgs e)
   at System.Windows.Forms.ComboBox.WmReflectCommand(Message& m)
   at System.Windows.Forms.ComboBox.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.9151 (WinRelRS6.050727-9100)
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v2.0.50727/mscorlib.dll
----------------------------------------
ASCOM.Utilities
    Assembly Version: 6.0.0.0
    Win32 Version: 6.5.1.3234
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/ASCOM.Utilities/6.0.0.0__565de7938946fba7/ASCOM.Utilities.dll
----------------------------------------
System
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.9149 (WinRelRS6.050727-9100)
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Core
    Assembly Version: 3.5.0.0
    Win32 Version: 3.5.30729.9141 built by: WinRelRS6
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System.Core/3.5.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
Microsoft.VisualBasic
    Assembly Version: 8.0.0.0
    Win32 Version: 8.0.50727.9149 (WinRelRS6.050727-9100)
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/Microsoft.VisualBasic/8.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualBasic.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.9149 (WinRelRS6.050727-9100)
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System.Windows.Forms/2.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.9149 (WinRelRS6.050727-9100)
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System.Drawing/2.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
Accessibility
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.9149 (WinRelRS6.050727-9100)
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/Accessibility/2.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
ASCOM.Exceptions
    Assembly Version: 6.0.0.0
    Win32 Version: 6.5.1.3234
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/ASCOM.Exceptions/6.0.0.0__565de7938946fba7/ASCOM.Exceptions.dll
----------------------------------------
ASCOM.QHYCCD.Camera
    Assembly Version: 21.2.20.12
    Win32 Version: 21.02.20.12
    CodeBase: file:///C:/Program%20Files%20(x86)/Common%20Files/ASCOM/Camera/ASCOM.QHYCCD.Camera.DLL
----------------------------------------
ASCOM.DeviceInterfaces
    Assembly Version: 6.0.0.0
    Win32 Version: 6.5.1.3234
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/ASCOM.DeviceInterfaces/6.0.0.0__565de7938946fba7/ASCOM.DeviceInterfaces.dll
----------------------------------------
System.Configuration
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.9153 (WinRelRS6.050727-9100)
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System.Configuration/2.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.9149 (WinRelRS6.050727-9100)
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System.Xml/2.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by mworion** [comment]
Just a ping: no clue so far

**Comment by mworion** [comment]
Please have a look to [https://www.10micron.eu/forum/viewtopic.php?f=18&p=12796#p12796](url) as it might be a solution for your problem , too. If not, please try to test with newest version and reopen.

Michel
