### ISSUE TITLE
Start mount not working

### ISSUE THREAD

**Issue by ACMBakx** [mworion/MountWizzard4#169]
From within MW4 I cannot wake the mount.
I can start the mount with a external WOL app.

Shutting down the mount is OK.

**Comment by mworion** [comment]
Arie,
what settings do you have for WOL B Adress and WOL B port ?
Please empty this fields and try again.
Michel

**Comment by ACMBakx** [comment]
![MW$Bootmount](https://user-images.githubusercontent.com/59890758/129488638-8660009c-9717-4858-999c-42a8594a569d.JPG)
The settings in MW4 and the WOL seem identical to me.
Yet the mount does not respond to the send bootmount command.
What you see in the info window is that the mount did start up using the WOL app.

**Comment by ACMBakx** [comment]
When I empty the fields as you propose, still nothing happens.

**Comment by mworion** [comment]
Arie,
I remember you already had it work. In my setup I do not see any issue. You also could set the broadcast to 255.255.255.255 in WOL B Adress and port 9 in WOL B Port, but that's anyway the default setting if you empty the fields. I added the logging in v40 to check more, but I tried any combination and got the mount booted.
Michel

PS.: There is one guess: if there is a space left in the empty fields or a training or leading space, it throws an error (in the log). This is fixed in v40.

**Comment by ACMBakx** [comment]
When I empty the 2 fields, should they auto populate when I restart MW4?
That does not happen. They remain empty.
With empty fields there is no response from the mount.

I put in exact the same 255.255.255.255 and 9 from the WOL app, in both fields, but still no response.
The WOL app gives a immediate response from the mount starting up.

Shutting down is ok. But that is a totally different protocol.

Again, no big deal for me, but I understand you want to know why.

**Comment by mworion** [comment]
Arie,
sure it should work I all cases as you have it working with a different solution which works. Sending the packet is not the big deal if the context is right. That's I have to find out. No MW4 will not populate it, it keeps it persistent and like Rüdiger needs some more tweaking.

But again, thanks for your intensive testing. v40 should get a chance.
Michel

**Comment by ACMBakx** [comment]
For the record.
192.168.2.255 is working now.

**Comment by mworion** [comment]
OK, saw it on the 10micron forum. Closing
