### ISSUE TITLE
MW4_Run fail

### ISSUE THREAD

**Issue by AstroTomB** [mworion/MountWizzard4#208]
Initial py install and MW4 run.
MW4_Run.bat fails with syntax error.
[install.log](https://github.com/mworion/MountWizzard4/files/7776195/install.log)
[mw4-2021-12-25.log](https://github.com/mworion/MountWizzard4/files/7776196/mw4-2021-12-25.log)
[run.log](https://github.com/mworion/MountWizzard4/files/7776197/run.log)

**Comment by mworion** [comment]
Hi Tom,
from what I could see is that you installation did not went into he virtual environment, but the system install. The list in install.log show an already installed version of MW4 already there. Both now mix up the system.
To check this, I put an extra output to the script. So please download the scripts again for next try.

Now some questions:
- Did you install python just for MW4? If so, please uninstall python app as well as launch app in your windows system and reinstall again. This cleans up the mixed installs on your system. Please check the "add python path" box during the python install.
- Did not work with MW4? If so, please remove the work dir and generate a new one. Otherwise generate a new one. You could copy exiting configs later as well.
- Did you already had a try for installation? If yes, this might explain some parts. Unfortunately the install and run logs are created new for each run, so I do not have a history what happened. So it is a good idea if you do not succeed in installation, just to use a new work folder for the next try.

The error message derives from the situation, that the installation went into the wrong place (see above) and the run script will start it from the right one (where no MW4 installation is present)

Hope this helps.

Michel

**Comment by AstroTomB** [comment]
Hi Michel,
Your insight was correct - py was clean installed for this initial install of MW4. I did check the path box.  However, I DID move the unzipped windows install bat files after install but before run. 
Followed your instruction and deleted/reinstalled py (checked path box). Deleted MW4 folder, created MW4_work and extracted new install scripts there. Ran from there without move. Alas, still failed. Did not attempt to reinstall (as I aslo did on first try).

**Comment by AstroTomB** [comment]
[run.log](https://github.com/mworion/MountWizzard4/files/7781074/run.log)
[install.log](https://github.com/mworion/MountWizzard4/files/7781075/install.log)
[mw4-2021-12-27.log](https://github.com/mworion/MountWizzard4/files/7781076/mw4-2021-12-27.log)
![Screenshot (38)](https://user-images.githubusercontent.com/96664588/147493028-32b0426c-af89-4cab-b280-ea3e0520be46.png)

**Comment by AstroTomB** [comment]
Hi Michel,
Just uploaded to github new logs.
Your insight was correct - This was first install of of py and MW4. I DID copy the extracted folder after install but before run... After failure also tried to reinstall.... So
I followed your suggestions and uninstalled py and lancher, and clean re-installed py (psth box checked).
Deleted original MW4 folder, created new MW4_work, downloaded and extracted new windows install. Ran install, seemed to complete OK. Ran run (same location, no move or anything else. Failed. Did not try / run anything else, uploaded logs and screenshot to github.
Hope this helps,

Thomas Blog
Cell: (505) 920-8785
This message sent with 100% solar generated electrons

________________________________

**Comment by mworion** [comment]
Hi Thomas,
first with the new install everything went in the right locations -> problem solved.
But there is another strange topic, which is related to an imported library changed during the last weeks. This leads to the related error. I had to implement a workaround in the scripts. So procedure is now more simple: please download the new scripts, extract them to the work folder, delete venv folder and run install again. After that MW4 will run.
Michel

**Comment by AstroTomB** [comment]
Hi! Installs and shows MW4 main screen and local functions. Will uncover/connect to mount for detailed test asap. Currently bad weather. Thank you!Tom BlogIn motion.On Dec 27, 2021 1:26 PM, Michael ***@***.***> wrote:
Hi Thomas,
first with the new install everything went in the right locations -> problem solved.
But there is another strange topic, which is related to an imported library changed during the last weeks. This leads to the related error. I had to implement a workaround in the scripts. So procedure is now more simple: please download the new scripts, extract them to the work folder, delete venv folder and run install again. After that MW4 will run.
Michel
