### ISSUE TITLE
Large amount of error when plate solving

### ISSUE THREAD

**Issue by Raddock** [mworion/MountWizzard4#24]
Tonight I put on my 102mm refractor. And despite the issue with the binning that was fixed, I'm still seeing a large amount of error with each plate solve. This log should show when running a 32 point model that most points have large amounts of error. Polar align was pretty good. I ran the optimize model after it completed as Model RMS was around 800-900. Optimizing the model deleted almost all the points except for 8, and now the model RMS says 4.3 with polar align error 1.31 arc min. Any suggestions to why this might be? My refractor sits very close to the saddle compared to my larger scopes, would this have anything to do with it?

[mw4-2020-04-26.log.zip](https://github.com/mworion/MountWizzard4/files/4537333/mw4-2020-04-26.log.zip)

**Comment by mworion** [comment]
Could you post the model file as well ? It's under the directory /model in the work folder. Thank I'm able to program the same model to my mount and can compare....

**Comment by Raddock** [comment]
Thanks for taking a look. Here's the model file, along with the points I used to create it, and a new log, because I woke up this morning and it was crashed.

[Archive.zip](https://github.com/mworion/MountWizzard4/files/4539375/Archive.zip)

**Comment by mworion** [comment]
Andrew,
the crash I can't review. The log without any hints stopped at some point in time. If you have seen something on the terminal, that would be good. Anyway I go the long way doing automated stress tests hopefully next weekend to find something which I could fix.

I could load the model. The only thing I've seen was a focal length set to 100mm ? Which might be a very wide field. But anyway this might only lead in not solved, but this did not happen. The deviations are very high. I've never seen this on this broad distribution with my 570mm focal length. 

My thoughts about this: there is too much distortion (although you might have a flat field on the ccd), which is not corrected and this is not correctly solved (because distorted). If so you might try another solver (ASTAP) for another test. If you keep the images, we could check this later on either with astrometry.net online or a windows toll called PinPoint (which does some type of distortion correction before solving. Checking this. If I know something I let you know.

Michel

**Comment by Raddock** [comment]
I only have this image left over from that session. I must have deleted the other images, because my drive was filling up with them. I do have a flat field corrector installed on this scope. Focal length should have been 571.2mm. A .8x reduction from 714mm focal length. The attached image was a bin 3 image. I'll have another clear night in two days and I'll try again. 

[2020-04-27-02-02-02-exposure.fits.zip](https://github.com/mworion/MountWizzard4/files/4541592/2020-04-27-02-02-02-exposure.fits.zip)

**Comment by mworion** [comment]
Hi Andrew,

interestingly I tested your image with 3 different solvers:
1: ASTAP
2: KStars - Astrometry.net
3: Cloudmakers - Astrometry.net
4. nova.astrometry.net Online - Astrometry.net

where 1, 2, 4
[Archiv.zip](https://github.com/mworion/MountWizzard4/files/4547812/Archiv.zip)
 show similar results (with small errors) and 3 is different with high errors. I attach the WCS files from 2 + 3 for you. Some parts are identical, some very different. This explains your problem. My recommendation: move to ASTAP or KStars as I use them, ASTAP on a regular bases and I had noch problems.

I posted this to cloudmakers for check as well. We'll see what's the outcome.

Michel

![Bildschirmfoto 2020-04-28 um 20 05 58](https://user-images.githubusercontent.com/6632980/80523833-f6f78780-898e-11ea-95f6-500f244e051e.png)

**Comment by Raddock** [comment]
Interesting. So the solve that provided the largest error was Cloudmakers? I thought I had it set to KStars. Maybe somehow I switched this, as I never got errors like this before. I'll try switching it back to KStars or ASTAP. I find ASTAP doesn't always work unless there's a lot of stars. Longer exposures are sometimes required. But good to know anyway. Hope there's some solution from Cloudmakers.

**Comment by mworion** [comment]
Andrew,

in the log there was Cloudmakers set. Peter from cloudmakers response was that he has no final clue why this happens. 

Michel

**Comment by Raddock** [comment]
Ok, thanks for looking into it. I'll consider this solved, and use KStars or ASTAP from now on.
