### ISSUE TITLE
MW4 presents itself as a small window only

### ISSUE THREAD

**Issue by pieterkoolen** [mworion/MountWizzard4#253]
Yesterday evening mw4 showed itself in a normal format which I could minimize/maximize on screen.
Tonight only a small window appeared. Restarting my PC did not bring any improvement.
I use an Eagle4 Pro under Windows 10.
No changes were made since last night.
What to do?
![18362DF2-8319-48FB-AADB-1D8E686E3511](https://user-images.githubusercontent.com/108614844/183150974-0bf5acc4-b62d-4ff9-b942-ee47a317e806.jpeg)

**Comment by mworion** [comment]
Hi Pieter,
does the screenshot show the small window or the window you normally expected. 
Did you change DPI High definition scaling on windows itself since the last start ?
If so, in the windows run script there are entries for font and dpi scaling, which could change the appearance if windows setting changed. This are the last lines:

```
SET QT_SCALE_FACTOR=1 >> run.log 2>&1
SET QT_FONT_DPI=96 >> run.log 2>&1
```

Michel

**Comment by pieterkoolen** [comment]
Hi Michael. 
This is the small window. Before the window was much bigger. 
I did not change anything. The day before the window was big when I switched off. Turning on next day small. Regards
Pieter

Verstuurd vanaf mijn iPhone

**Comment by pieterkoolen** [comment]
Btw other app windows do not have this anomaly

Verstuurd vanaf mijn iPhone

**Comment by pieterkoolen** [comment]
Michael
This is my line:

Verstuurd vanaf mijn iPhone
Regards
Pieter

**Comment by pieterkoolen** [comment]
Hi Michael,
With some help from Nicolas I changed the scale factor to 2.
Problem solved.
However it is still a little weird.
When I now minimize the window it does not minimize however jumps to the right upper corner of the screen. But that is not a problem.
Thx
Pieter

Verstuurd vanaf mijn iPad

**Comment by mworion** [comment]
Hi Pieter,
good to hear that you found a good setup. The jump is somehow wired. If you don't mind, please post your config file (*.cfg) here. I try to check this if I see the jump, too.
Michel

**Comment by pieterkoolen** [comment]
Hi Michael, 
Here it is



Pieter

**Comment by mworion** [comment]
Sorry,
if you just put it in the reply, it won't reach me. You have to drop it in the web interface...

**Comment by pieterkoolen** [comment]
I dropped it in my repository.
Hope it works.
This is quite new technology for me

**Comment by mworion** [comment]
Hi Pieter,
yes worked. Even simpler, you could drop it in this issue (will work as well).
So there is one topic I found which I will address in future from release 3.0 on, but not in the current 2.x: 
When closing, MW4 stores the window positions for the next run regardless of the positions themself. In your config I saw some negative value, which indicate that you moved the main window a little bit left and top out of the screen for some pixels.
When opening MW4, it will set the windows position to the same values, which in windows does not really work. Also other platform like linux and Mac I've seen behave different.
As result some wired things happen. 
In future I will limit the screen positions to the visible screen and move them accordingly so that the window managers don't see any negative or too large number.
Michel

**Comment by pieterkoolen** [comment]
thx

**Comment by mworion** [comment]
On windows, HDPI scaling is a strange thing. Apps support it or not. And the implementation of supporting it might differ as well. But did you enable HDPI features on your eagle since the last correct ( meaning large window) start ?
