### ISSUE TITLE
MW suddenly disappears from the screen, hemisphere tab does not respond to min/max

### ISSUE THREAD

**Issue by pieterkoolen** [mworion/MountWizzard4#261]
While working with MW it suddenly disappears from the screen.
The hemisphere tab is not responding properly on min/max.
Somehow it appears the problems are related

I work under windows 11

I attached the log
[mw4-2022-08-20.log](https://github.com/mworion/MountWizzard4/files/9387870/mw4-2022-08-20.log)

Feel free to log in my computer.

**Comment by mworion** [comment]
Hi Pieter,
I try to check an a windows11 install as well. Do you have any further observations? Could you reproduce it in a simple manner? Did you have this behavior since the beginning or did it start at some point in time? If so, do you remember anything you might have changed in the setup of MW4 (drivers, devices) or even your computer?

I do not see the original crash (if one happened), but only things afterwards when windows closing not nicely. These are cause by an external library. Ich check, what I could find out.
Thanks for offering login. I'm out today, perhaps I'll come back to you.

**Comment by pieterkoolen** [comment]
Hi Michael. Last night at happened twice while building models. I noted the times of occurrence. Will upload the files and times later today. 
Regards
Pieter

Verstuurd vanaf mijn iPhone

**Comment by pieterkoolen** [comment]
[mw4-2022-08-20.log.zip](https://github.com/mworion/MountWizzard4/files/9413651/mw4-2022-08-20.log.zip)

**Comment by pieterkoolen** [comment]
Hi Michael,
I just uploaded again.
Seems something did not work day before.
Did you receive it now?

**Comment by pieterkoolen** [comment]
Hi Michael,
you have been able to give it some thoughts?

**Comment by mworion** [comment]
Hi Peter,
so far no further clue beside the fact I know now, that this could happen, because an exception could crash python itself and then all the logging stuff does not write anything to a file anymore. In version 3 I tried to replace some libraries who might be corner cases during MW4 usage and therefore critical.

Sorry to say, but I have no solution for this issue
Michel

**Comment by mworion** [comment]
Yes, many thanks
Michel
