### ISSUE TITLE
MW4 3.2.7b1 reporting -1189 Ortho Error consistently and GOTOs are off by that amount in Declination

### ISSUE THREAD

**Issue by JDAstroPhoto** [mworion/MountWizzard4#368]
**Describe the bug**
MW4 3.2.7b1 is reporting -1189 Ortho Error consistently and GOTOs are off by that amount in Declination.

**To Reproduce**
Happens with  parallels of declination, for alignment and Grid.  
It occurs with all number of points.  It is also verified in the handset, same high ortho error.

I checked the hardware with the 10 micron tools in NINA and built a model with them immediately after all the MW4 Tests. 10 micron tool model build report out correct 15.84 arc seconds ortho error and GOTOs are spot on.  I've done the MW4 testing over 4 nights and consistently get the large ortho error and GOTOs that are off in declination with 3.2.7b1

Comparison below with the 10 micron model builder in NINA with 3.2.7b1
Table heading : NINA 10micron tools model build -  MW4 3.2.7b1
Stars 50 - 65
RMS 7.1 - 4.5
model 11 - 11
PA Error Angle 81.79 - 76.57
PA Alt Error 4.34 - 9.74
Polar Alt 33.156 - 33.1579
Polar AZ 359.9902 - 359.9864
**_Cone Error (Ortho error) 15.84 - -1189.08_**
PA Error 29.88 - 42.12
PA Az Error -35.28 - -48.96

**Comment by mworion** [comment]
Hi,
could you please add the MW4 logfile. Many thanks,
Michel

**Comment by JDAstroPhoto** [comment]
Ok, new information.  I've been running MW4 3.2.6, 3.2.7b1 and 3.2.7b2 now for almost 2 weeks.  Here are my results.
MW4 3.2.26 and 3.2.7b1 exhibit the following:
1. The first time you run MW4, it works great, ortho error 10 seconds Polar alignment error 15 seconds.
2. Run it again with 65 - 98 points it might be ok
3. For sure run it a third time with any number of points, then your ortho error 1175 seconds and your GOTOs are off  by 1/3rd of a frame.
MW4 3.2.7b2
1. It ran great the first time last night.

It seems like a memory leak somewhere that happens if you keep MW4 running and must be feeding bad information to the mount.  If you bring MW4 down and back up again, it works fine.  I am currently imaging in Bortle 1 skies since Monday.  My new process is now to only run MW4 once, if I want to run it again then I will bring it down and back up again.

**Comment by mworion** [comment]
Thanks for the update. This sounds strange as python does memory management on it’s own. Let me check what is going on. I try to setup a repeadable test with multiple models after each other to find out. MichelAm 04.09.2024 um 22:16 schrieb JDAstroPhoto ***@***.***>:﻿
Ok, new information.  I've been running MW4 3.2.6, 3.2.7b1 and 3.2.7b2 now for almost 2 weeks.  Here are my results.
MW4 3.2.26 and 3.2.7b1 exhibit the following:

The first time you run MW4, it works great, ortho error 10 seconds Polar alignment error 15 seconds.
Run it again with 65 - 98 points it might be ok
For sure run it a third time with any number of points, then your ortho error 1175 seconds and your GOTOs are off  by 1/3rd of a frame.
MW4 3.2.7b2
It ran great the first time last night.

It seems like a memory leak somewhere that happens if you keep MW4 running and must be feeding bad information to the mount.  If you bring MW4 down and back up again, it works fine.  I am currently imaging in Bortle 1 skies since Monday.  My new process is now to only run MW4 once, if I want to run it again then I will bring it down and back up again.
