### ISSUE TITLE
RIP MW4

### ISSUE THREAD

**Issue by ACMBakx** [mworion/MountWizzard4#42]
This morning MW4 was up and running.
This afternoon it did not start anymore........
Run.bat   Update.bat nor Install.bat are stopping after a initial startup.
The dome driver is started btw.
Attach the last log.

Arie
[mw4-2020-06-01.log](https://github.com/mworion/MountWizzard4/files/4712943/mw4-2020-06-01.log)

**Comment by ACMBakx** [comment]
Fixed. It is running again.
Somehow a corrupted horizon points file was created by me.
Deleted it and now MW starts up again.

**Comment by mworion** [comment]
Arie,
thanks for the log. The were two issue seen in the log and I added test against it. 
- Reason was (for start) that if you had more than 5 retries to connect to an ASCOM driver -> MW4 will stop.
- Horizon file: I check boundaries, but I missed the case checking an empty one.

Fixed in the next beta.
Michel
