### ISSUE TITLE
Wrong pop-up label a.o.

### ISSUE THREAD

**Issue by ACMBakx** [mworion/MountWizzard4#44]
v0.150.25b5
Some observations:

"Auto sort points"
When hovering with the mouse over "Avoid meridian flip when starting", a wrong pop-up appears.
It is the one identical to "Auto delete points below horizon"

When I build my model I did check "Delete model before start of model build"
But my existing model was replaced by the new model nevertheless.

Is this intended to allow a small model to be expanded with more points?

When I am looking at the "Manage model" windows I see the "models stored in mount computer" alphabetically listed. But what is the "Actual Mount Model" that I am currently looking at? I see no label for that.

Arie

**Comment by mworion** [comment]
Arie,
Tooltip is fixed, thanks for the hint.

Delete model before start of model build does not keep the actual one. If you want so, please check "Enable model backups before program". 

There are two possibilities doing the model: Having non acting (cleared) and therefore no pointing correction in place and modeling without clearing it, which means you have an acting model, which does correction right now until it is "over programmed" by the mount.
I raised questions to Filippo, what the difference in behavior and resulting model it will be, but so far no answer.

Unfortunately the actual model in the mount computer has no name and no tag. That's a point to be improved by 10micron. If I do backups, I store now the actual model under "actual", but this is not an ideal solution, because if you manually (even through MW4) change models (delete, add etc.) it looses sync.

Michel

**Comment by mworion** [comment]
0.150.25b6 fixed
