### ISSUE TITLE
Request: Export and Import user data / or dedicated path for user data

### ISSUE THREAD

**Issue by Ruediger3** [mworion/MountWizzard4#55]
Hi Michel,
I'd like to suggest a function to export and import user data:
- Profiles
- Models
- Build and Mask points

Alternatively (what would be better) provide the possibility to store the value data at dedicated path.

This would make backup much easier since user data is backed up daily, but applications only once a week. It would also make it easier to re-install the App without loosing value data. Generally splitting application and user data is always a good idea.

Thanks!
Rüdiger

**Comment by mworion** [comment]
Hi Rüdiger,
I thought about this when I started, but decided to go the way I did it.

Reasons: 
There is already a split between app and data. App is all in venv folder, all the rest is user data. So if you only would like to backup user data, exclude venv folder from the daily backup list.

You could have multiple installations even with different versions at the same time (and btw, if performance of the computer, mount and network allows, run them in parallel)

Like you other request adding data (and in general improving the app over time) enforces me to keep compatibility between multiple instances of the app and the user data. 

Mixing right now is easy, because you just have to copy files. So I will not go for a full blown design which does not really add basic features. 

Michel

**Comment by Ruediger3** [comment]
Hi Michel,

thanks for explaining. I was asking, since there are more folders not containing users data (e.g. docs, support, gists ...) outside venv, so I was not sure. Also the logs exceeding meanwhile more than 14 GB, due to the log level. Therefore I wanted to separate the user's data, since I mirror backup data over WAN and therefore I keep it as little as possible.
I will modify backup for dedicated folders. No problem. But I think about less IT affine people. When they reinstall, they will lose all data. Usually Windows takes care about user's data in the specific folders. 
For me it is ok, hence I close the issue.
