### ISSUE TITLE
mountWizzard4 connection to mount unstable

### ISSUE THREAD

**Issue by kaythriemer** [mworion/MountWizzard4#7]
Hi,
I am trying to familiarize with mountwizzard4.
I own a 10micron GM2000HPS.
The installation on Ubuntu 18.04 was easy after installing the dependencies using your script MW4_Install.sh.

As first I tried to connect the mount. I filled the IP address and MountWizzard seemed to be connected to the mount (Mount is shown green and the Telescope pointing coordinates are filled. Also the values in "Status and settings from mount computer" are filled.
But if I try to connect the Keypad, it only shows a "Connecting...."
![MountWizzard4](https://user-images.githubusercontent.com/28596048/72760381-d9b95d00-3bd8-11ea-9149-3ed2b55b8554.png)

When I check the Hand Control of the mount , the Network symbol is blinking randomly. Normally the Network symbol is shown always, if a computer is connected to the mount.
(I also use KStars and Ekos on this Ubuntu 18.04. KStars/Ekos is able to connect to mount. That means all the Hardware, LAN-Cable,... seams to be error-free.)

I set the Logging to Deep Debug, but I cant find something helpful in the LOG:
[2020-01-20 22:36:07][C][      loader.py][ 299] ----------------------------------------------------
[2020-01-20 22:36:07][C][      loader.py][ 300] 
[2020-01-20 22:36:07][C][      loader.py][ 301]  MountWizzard 4.0 started !
[2020-01-20 22:36:07][C][      loader.py][ 302] 
[2020-01-20 22:36:07][C][      loader.py][ 303] ----------------------------------------------------
[2020-01-20 22:36:07][C][      loader.py][ 304]  Platform         : Linux
[2020-01-20 22:36:07][C][      loader.py][ 305]  Release          : 4.15.0-74-generic
[2020-01-20 22:36:07][C][      loader.py][ 306]  Machine          : x86_64
[2020-01-20 22:36:07][C][      loader.py][ 307]  CPU              : x86_64
[2020-01-20 22:36:07][C][      loader.py][ 308]  Python           : 3.7.5
[2020-01-20 22:36:07][C][      loader.py][ 309]  PyQt5            : 5.13.2
[2020-01-20 22:36:07][C][      loader.py][ 310]  Qt               : 5.13.2
[2020-01-20 22:36:07][C][      loader.py][ 311]  Node             : tempo-ThinkPad-W530
[2020-01-20 22:36:07][C][      loader.py][ 325]  Hosts            : ('tempo-ThinkPad-W530', [], ['127.0.1.1'])
[2020-01-20 22:36:07][C][      loader.py][ 327]  Environment is   : live
[2020-01-20 22:36:07][C][      loader.py][ 328]  Actual workdir   : /home/lux/MountWizzard4
[2020-01-20 22:36:07][C][      loader.py][ 329]  Bundle dir       : 
[2020-01-20 22:36:07][C][      loader.py][ 330]  mountwizzard4    : 0.145
[2020-01-20 22:36:07][C][      loader.py][ 331]  indibase         : 0.123
[2020-01-20 22:36:07][C][      loader.py][ 332]  mountcontrol     : 0.151
[2020-01-20 22:36:07][C][      loader.py][ 333]  sys.executable   : /home/lux/MountWizzard4/venv/bin/python
[2020-01-20 22:36:07][C][      loader.py][ 335] ----------------------------------------------------
[2020-01-20 22:36:07][C][      loader.py][ 336] 
[2020-01-20 22:36:07][I][     obsSite.py][ 205] Loader: expire:[False], dir:[/home/lux/MountWizzard4/data]
[2020-01-20 22:36:07][I][  astrometry.py][ 195] binary and index files available for astrometry.net local
[2020-01-20 22:36:07][I][  astrometry.py][ 185] /usr/local/astrometry/bin/solve-field not found
[2020-01-20 22:36:07][I][  astrometry.py][ 185] /opt/astap/astap not found
[2020-01-20 22:36:07][I][  astrometry.py][ 190] no index files found
[2020-01-20 22:36:08][I][     kmRelay.py][  94] Host value not configured
[2020-01-20 22:36:36][W][      loader.py][ 169] Click Button  : [openKeypadW]

Any idea, what can be wrong ? Or how can I debug more in detail?

CS,
Kay

**Comment by mworion** [comment]
Hi Kay,

some points about your observations:
The virtual keypad has to be enabled in the settings menu of the mount (via the real handpad). There is a menu called network services. 
Second (and from my point that's a bug on 10micron side and I told them): when you attach a real handpad, there network services one is disabled. So I have to remove my physical one to get connected)
On my mount the network symbol is blinking as well. That does not matter at all. My guess is that the symbol reflects network activity. MW4 does a lot of communication with the mount continuously, so network activity should be always there. 
As soon as you see the green light for mount, the connection should be there and stable. I recommend a wired link, no WiFi because of that traffic.

Michel

**Comment by kaythriemer** [comment]
Hi Michel,
thank you for the fast reply.
I was unsure if Mountwizzard is correct connected, because if  I connect KStars/Ekos with the mount, the network symbol on hand controller is constantly switched on. Yes, I am using a wired link, no WiFi.

I will check if the virtual keypad is enabled, but I think so, because I am able to use the "original" Virtual Handpad provided by 10micron using a Windows machine.

Do you mean, if I connect a wired network for mount control I have to remove the handpad ?
If I use KStars/Ekos I am able to use both ways to control the mount, either the physical real handpad or the PC.

I will check again the settings and keep you informed.

Thank you.

Kay

**Comment by mworion** [comment]
Kay,

removing the Handpad physically is only necessary if you would like the virtual handpad through MW. You could check when accessing the mount via Webbrowser. For the functionality of MW4 in core it's irrelevant if you have the handpad connected.

Michel

**Comment by ACMBakx** [comment]
FWIW
I connect multiple Hand controllers. The physical one, the remote one, the web one and the MW one.
They all work simultanious.
[bandicam 2020-01-21 17-03-11-889.zip](https://github.com/mworion/MountWizzard4/files/4092001/bandicam.2020-01-21.17-03-11-889.zip)

Arie

**Comment by kaythriemer** [comment]
Hi Arie, 
thank you for your video. 

I will check on my Windows PC, if I am able to connect the mount as you shown in your video.

But it will not be possible during the week. I will try on weekend.

Kay

**Comment by kaythriemer** [comment]
Hi Michel,
 today I did some new tests with MountWizzard4 and the brand new release 0.147.1 :-)
I was not able to get the keypad of MountWizzard4 (Windows7 or Ubuntu 18.04) connected. 

I used wireshark to get more details and I found out:
MountWizzard4 connects to mount using TCP/IP port 3492.
ModelCreator from Martin is using port 3490.
In KStars/Ekos I configured also port 3490.
I also tried the "original" 10Micron Virtual Keypad (on a Windows machine), it uses port 3491.
The port 3491 is also described in the 10Micron documentation.
-----
quote
When using the LAN connection, the Virtual Keypad software communicates with the mount using
the TCP/IP port number 3491.
----
For software connections port 3490 or 3492 is used
----
quote
If you want to use the Ethernet or Wireless connection over port 3490 or 3492 with a software supporting the serial link, you can use a virtual serial port software such as HW Virtual Serial Port (http://www.hw-group.com/products/hw_vsp/index_en.html).
-------

But, if I try to connect the keypad of MountWizzard4, it will connect to port 8000. 
But connection to port 8000 is refused.
I assume this is what you mean, that the virtual keypad hast to be enabled via the real keypad.
The only thing, that I found in "Network Services", is to activate "Remote assist". But I think, this is not, what you mean.

I am using 10Micron mount version 2.16.4

Sorry I do not want to be the know-it-all guy (Klugscheisser ;-) ) but could it work if your virtual keypad connects to port 3491 ? 
I am very impressed from your work you have done with MountWizzard4.

There is another thing I want to ask.
I just started to use KStars/Ekos and indi and I am not so familiar with the internals.

Is it necessary to start the indiserver including the driver for mount, camera, etc. which I want to use in MountWizzard4 ?
I identified, that MountWizzard4 is able to connect to the mount if I do not start the indiserver before. But to get the camera connected it is necessary to have a running indiserver.
I am confused.

Can you give me a hint, if I have to start the indiserver by myself or not ?


Thank you,
Kay

**Comment by mworion** [comment]
Hi Kay,

saw you posting right now. MW4 keyboard is "just" a browser application which uses the official 10micron keyboard, which ist offered for any browser on the ip of your mount. I integrated it just for the point, that I don't want to open another application when doing astro imaging. You could give it a try to connect to your mount via browser (just the ip of the mount). Never looked it up, but the default port of a webpage might be 8000. So everything is ok. One point to keep in mind: first you have to enable the net services in your mount (under network settings). This might be the reason which it is not open.

MW4 could be started and run without INDI server running. But sure you need it running for all other equipment. MW4 starts or stops the server not automatically. Why: There might be some other equipment using the server and as MW4 is not the main application for imaging I avoid doing things automatically which might interfere with others.

I my setup (and I have a small computer on my rig), the server is started directly on boot as it runs only when I would like to work with the scope. So that's easy. Don't know your setup, but having the server up and running all the time does not really hurt.

Michel

BTW: I choose port 3942 just for the sake that all other programs do not use it, so checking things with wireshark becomes a little bit easier.

**Comment by kaythriemer** [comment]
Hi Michel,
thank you for your support.
I updated to v2.16.11 and now it is possible to access the mount via WEB Browser and to connect the Virtual Keypad from MountWizzard4.  :-)
The http default port  is 80 but 10Micron uses 8000.

Thank for your indi support. I will keep it in mind.

Kay
